- www/helpers.py
- www/tests.py
> [fix] Current academic year was wrong

- templates/skel.html
> [enh] hr in footer

- static/style/main.css
No double background color on hovering, better use of space.
> [fix] weird sidebar display

- notify/tasks.py
- notify/tests.py
* Refactor de la propagation des notifications, pour couvrir le cas de l'ajout de commentaires sur des documents
* Ajout de tests
> [fix] Notifications propagation

- telepathy/views.py
> [fix] id is a function (not the id of a db object)

- README.md
Add npm and library for `Ubuntu`
> Add dependencies

- Procfile
- static/scripts/course.jsx
Added download button directly on the document list page.
> Download Button

- catalog/views.py
- integration/test_webtest.py
- templates/catalog/category.html
Cliquer sur le mnémonique pour s'abonner ou se désabonner d'un cours depuis la page d'une catégorie
> 1-click follow

- templates/users/settings.html
- users/urls.py
- users/views.py
- www/config/default.py
> Add tokens to DRF

- catalog/views.py
- search/apps.py
- search/logic.py
- search/migrations/0001_setup_extensions.py
- search/rest.py
- search/serializers.py
- www/config/default.py
- www/rest_urls.py
> Enhance search and add an API

- assets/search/Search.js
- assets/search/index.js
- package.json
- templates/catalog/course_search.html
- templates/home.html
- webpack.config.js
Maybe we should put this search bar on the top in the menu bar when @titouanc finish the new tree menu
Ready to merge but @C4ptainCrunch need to change the logic of query (memonic not recognized)
> [add] Search bar autocompleting using the API.

- assets/courses/CourseDocumentList.js
Unsure about line 130 though, will single-quote be treated as is or as string start ?
> Two small typos

- documents/rest.py
- requirements.txt
Broken since 3.8 deprecated detail_route decorator.
> Upgrade DRF

- Makefile
- catalog/management/commands/loadtree.py
- catalog/slug.py
- catalog/tests/load_tree_test.py
- requirements.in
- requirements.txt
- setup.cfg
> Remove dependency to libulb (that is broken since the new catalog) so we can import a new tree

- .dockerignore
- .gitignore
- 500.html
- build.sh
- catalog/templates/catalog/course.html
- docker/Dockerfile
- docker/celery.sh
- docker/docker-compose.dev.yml
- docker/docker-compose.yml
- docker/entrypoint.sh
- docker/nginx/Dockerfile
- docker/nginx/nginx.conf
- docker/web_startup.sh
- documents/templatetags/like_tags.py
- static/home.js
- static/main.js
- static/styles/style.css
- www/templates/finder/bloc.html
- www/templates/finder/fac.html
- www/templates/finder/programs.html
> Add preliminary support for Docker

- catalog/templates/catalog/course.html
maintenant c'est fix  et ca ressemble a
> [FIX] button wrap

- catalog/templates/catalog/course.html
Useful if the user has already selected tags or typed a filter, so they keep it
> Put the "favorite" button of a course inside a turbo-frame so that clicking on it avoids a full replace of the DOM.

- Makefile
- README.md
Also, use python3 and not python in the Makefile in case some users do not have a symlink.
> Make it clear that the installation instructions are normally complete and if not, it's considered a bug

- documents/forms.py
- documents/templates/documents/document_edit.html
- documents/templates/documents/document_upload.html
- static/main.js
This should avoid the bug where TomSelect is initialized before the input exists.
> Add a new stimulus controller that is responsible to call the initialization of TomSelect

- .pre-commit-config.yaml
- documents/admin.py
See https://adamj.eu/tech/2022/10/26/django-upgrade-mega-release/ for an explanation of the tool and its features.
> Add django-upgrade as pre-commit

- documents/templates/documents/viewer.html
- static/main.js
Closes #278.
Works only on mobile (or desktop safari), due to browser support. Button is not shown on devices not supporting it.
> Add a share button to the viewer

- catalog/views.py
- documents/admin.py
- documents/templates/documents/document_edit.html
- documents/views.py
> Allow users to hide document form the course document list

- CHANGELOG.md
- CONTRIBUTING.md
> Add a contribution workflow

- CHANGELOG.md
- documents/templates/documents/document_upload.html
- www/templates/index.html
- www/templates/welcome.html
Fixes #302
This will be merged today, as there is pressure from the "département informatique" to do it very soon
> Make it clear DocHub is a student initiative

- CHANGELOG.md
- Makefile
I fixed the makefile for that he load correctly the tree and course + doesn't crash if user he try to create already exist
> Fix makefile

- .pre-commit-config.yaml
- requirements.txt
Fixes https://github.com/advisories/GHSA-3f63-hfp8-52jq
> Update dependencies + pre-commits
